name: youm-mission11
services:
  server:
    image: youm/mission11
    build:
      tags:
        - youm/mission11:1.0
      args:
        - NODE_VERSION=22.13.0
      dockerfile: Dockerfile
      pull: true
      context: .
    container_name: youm-mission11-container
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - network-mission11
    volumes:
      - volume-mission11:/public:rw

  db:
    image: postgres:15
    restart: always
    # env_file:
    #   - .env.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: express_user_system
    ports:
      - '5434:5432'
    networks:
      - network-mission11
    volumes:
      - volume-db:/var/lib/postgresql/data

networks:
  network-mission11:

volumes:
  volume-mission11:
  volume-db:
